# Generated by Django 6.1 on 2026-08-22 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etb",
            name="is_struck_out",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Gestrichen"
            ),
        ),
        migrations.AlterField(
            model_name="etb",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="etb_entries",
                to="missions.mission",
            ),
        ),
    ]
