# Generated by Django 6.1 on 2026-08-22 14:44

from django.db import migrations


def remove_delete_permission(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.using(schema_editor.connection.alias).filter(
        content_type__app_label="missions",
        content_type__model="etb",
        codename="delete_etb",
    ).delete()


def restore_delete_permission(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    database = schema_editor.connection.alias
    content_type = ContentType.objects.using(database).get(
        app_label="missions", model="etb"
    )
    Permission.objects.using(database).get_or_create(
        content_type=content_type,
        codename="delete_etb",
        defaults={"name": "Can delete Einsatztagebucheintrag"},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("missions", "0002_etb_is_struck_out_alter_etb_mission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etb",
            options={
                "default_permissions": ("add", "change", "view"),
                "ordering": ("-timestamp", "-pk"),
                "verbose_name": "Einsatztagebucheintrag",
                "verbose_name_plural": "Einsatztagebucheinträge",
            },
        ),
        migrations.RunPython(
            remove_delete_permission,
            restore_delete_permission,
        ),
    ]
