# Generated by Django 6.1.1 on 2026-09-22 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("missions", "0005_optional_operation_log_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapOverlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.TextField()),
                ("corners", models.JSONField()),
                ("opacity", models.FloatField(default=0.85)),
                (
                    "mission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_overlay",
                        to="missions.mission",
                    ),
                ),
            ],
        ),
    ]
