# Generated by Django 6.1.1 on 2026-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapoverlay",
            name="control_points",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
