# Generated by Django 6.1.1 on 2026-09-22 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_mapoverlay_control_points"),
        ("missions", "0005_optional_operation_log_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoJSONImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geojson_imports",
                        to="missions.mission",
                    ),
                ),
            ],
        ),
    ]
