# Generated by Django 6.1 on 2026-08-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mgmt", "0002_mission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mission",
            options={
                "permissions": (
                    ("frontend_view_mission", "Frontend: Missionen anzeigen"),
                    ("frontend_create_mission", "Frontend: Missionen anlegen"),
                    ("frontend_update_mission", "Frontend: Missionen bearbeiten"),
                    ("frontend_delete_mission", "Frontend: Missionen löschen"),
                )
            },
        ),
    ]
