# Generated by Django 6.1 on 2026-08-22 14:01

from django.db import migrations


FRONTEND_PERMISSIONS = {
    "frontend_view_mission": "Frontend: Missionen anzeigen",
    "frontend_create_mission": "Frontend: Missionen anlegen",
    "frontend_update_mission": "Frontend: Missionen bearbeiten",
    "frontend_delete_mission": "Frontend: Missionen löschen",
}


def remove_frontend_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.using(schema_editor.connection.alias).filter(
        content_type__app_label="mgmt",
        content_type__model="mission",
        codename__in=FRONTEND_PERMISSIONS,
    ).delete()


def restore_frontend_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    database = schema_editor.connection.alias
    content_type = ContentType.objects.using(database).get(app_label="mgmt", model="mission")
    for codename, name in FRONTEND_PERMISSIONS.items():
        Permission.objects.using(database).get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("mgmt", "0003_alter_mission_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mission",
            options={},
        ),
        migrations.RunPython(
            remove_frontend_permissions,
            restore_frontend_permissions,
        ),
    ]
