# Generated by Django 6.1 on 2026-10-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mgmt", "0008_remove_treatment_keyword_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="DischargeDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Aktiv"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entlassziel",
                "verbose_name_plural": "Entlassziele",
                "ordering": ("pk",),
            },
        ),
    ]
