# Generated by Django 6.1 on 2026-08-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mgmt", "0002_mission"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mgmt.genderenum",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="mgmt.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("keyword", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "treater_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "doctor_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "leaving_specified",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_order_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assigning_enum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mgmt.assigningenum",
                    ),
                ),
                (
                    "doctor_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatments_as_doctor",
                        to="teams.helper",
                    ),
                ),
                (
                    "leaving_enum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mgmt.leavingenum",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="mgmt.mission",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatments",
                        to="patients.patient",
                    ),
                ),
                (
                    "treater_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatments_as_treater",
                        to="teams.helper",
                    ),
                ),
            ],
        ),
    ]
