# Generated by Django 6.1 on 2026-10-03 09:24

from django.db import migrations, models


def preserve_existing_destinations(apps, schema_editor):
    Treatment = apps.get_model("patients", "Treatment")
    database = schema_editor.connection.alias
    treatments = Treatment.objects.using(database).select_related("leaving_enum")
    for treatment in treatments.iterator():
        destination = (treatment.leaving_specified or "").strip()
        if not destination and treatment.leaving_enum_id:
            destination = treatment.leaving_enum.name
        if destination:
            Treatment.objects.using(database).filter(pk=treatment.pk).update(
                discharge_destination=destination,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_patient_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="discharge_destination",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Entlassziel"
            ),
        ),
        migrations.RunPython(preserve_existing_destinations, migrations.RunPython.noop),
    ]
