# Generated by Django 6.1 on 2026-10-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_treatment_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="transported_by_public_ems",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Abtransport durch öffentlich-rechtlichen Rettungsdienst",
            ),
        ),
    ]
