# Generated by Django 6.1 on 2026-08-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helper",
            name="age",
        ),
    ]
