# Generated by Django 6.1 on 2026-08-25 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0005_optional_operation_log_fields"),
        ("teams", "0004_alter_helpermission_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "pk"),
            },
        ),
        migrations.AddField(
            model_name="helpermission",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="helper_missions",
                to="teams.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("mission", "name"), name="unique_team_name_per_mission"
            ),
        ),
    ]
