# Generated by Django 6.1 on 2026-08-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_team_helpermission_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpermission",
            name="planned_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="planned_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
