# Generated by Django 6.1 on 2026-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_helpermission_planned_end_date_team_planned_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
