# Generated by Django 6.1 on 2026-09-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_team_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
